## Backpacks configuration ##
# save-interval: how often to queue all loaded backpacks for saving
# save-per-tick: how many backpacks on a single tick
# save-tick-delay: # of ticks delay between each save-per-tick
# configured-world-only: require world in group.yml, or use default group if not configured
# maximum-backpacks-per-group: maximum backpacks a player can have per group
# inventory-title-format: format of inventory screen title on backpack
# backend: nbt or yaml. nbt is more performant, but requires the server and Backpacks version to be the same
# convert: nbt, yaml, or false. convert from this backend to the backend set above.
# debug: for debugging

save-interval: 500
save-per-tick: 3
save-tick-delay: 5
configured-world-only: true
maximum-backpacks-per-group: 8
inventory-title-format: "Backpack - &f%s"
backend: nbt
convert: false
debug: false
