name: ${project.name}
version: ${project.version}-b${build.number}
description: ${project.description}
main: me.darqy.backpacks.BackpacksPlugin
author: Darq_Alder
softdepend: [Lockette, Deadbolt]

commands:
  createpack:
    description: Creates a new backpack
    usage: /<command> (backpack) (player) (world)
    aliases: [newpack, cpack, packcreate]
  backpack:
    description: Opens the player's backpack
    usage: /<command> (backpack)
    aliases: [pack, knapsack]
  inspectpack:
    description: Opens a read-only version of a backpack
    usage: /<command> [player] (backpack) (world)
    aliases: [ipack, packinspect]
  listpacks:
    description: Lists a player's backpacks in a given world
    usage: /<command> (world) (player)
    aliases: [packs, knapsacks, listpack, packlist]
  packutils:
    description: Various utilities to help manage your backpack
    usage: /<command> [action] (p:[backpack])
    aliases: [upack, packutil]
  backpacks:
    description: Admin commands
    usage: /<command> [reload|backup]
permissions:
  backpacks.create.limit.bypass:
    default: false
